In [1]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

sum_AB = A + B
print("\nSum of A and B:\n", sum_AB)

diff_AB = A - B
print("\nDifference of A and B (A - B):\n", diff_AB)

prod_AB = np.dot(A, B)
print("\nMatrix multiplication of A and B:\n", prod_AB)

hadamard_AB = A * B
print("\nHadamard Product (element-wise multiplication of A and B):\n", hadamard_AB)

det_A = np.linalg.det(A)
print("\nDeterminant of A:\n", det_A)

try:
    inv_A = np.linalg.inv(A)
    print("\nInverse of A:\n", inv_A)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and does not have an inverse.")

transpose_A = np.transpose(A)
print("\nTranspose of A:\n", transpose_A)

pseudo_inv_A = np.linalg.pinv(A)
print("\nMoore-Penrose Pseudo-inverse of A:\n", pseudo_inv_A)

frobenius_A = np.linalg.norm(A, 'fro')
print("\nFrobenius norm of A:\n", frobenius_A)


Matrix A:
 [[7 1 9]
 [1 8 9]
 [1 8 5]]
Matrix B:
 [[7 8 5]
 [7 2 3]
 [6 2 3]]

Sum of A and B:
 [[14  9 14]
 [ 8 10 12]
 [ 7 10  8]]

Difference of A and B (A - B):
 [[ 0 -7  4]
 [-6  6  6]
 [-5  6  2]]

Matrix multiplication of A and B:
 [[110  76  65]
 [117  42  56]
 [ 93  34  44]]

Hadamard Product (element-wise multiplication of A and B):
 [[49  8 45]
 [ 7 16 27]
 [ 6 16 15]]

Determinant of A:
 -220.00000000000009

Inverse of A:
 [[ 0.14545455 -0.30454545  0.28636364]
 [-0.01818182 -0.11818182  0.24545455]
 [-0.          0.25       -0.25      ]]

Transpose of A:
 [[7 1 1]
 [1 8 8]
 [9 9 5]]

Moore-Penrose Pseudo-inverse of A:
 [[ 1.45454545e-01 -3.04545455e-01  2.86363636e-01]
 [-1.81818182e-02 -1.18181818e-01  2.45454545e-01]
 [ 4.71841798e-17  2.50000000e-01 -2.50000000e-01]]

Frobenius norm of A:
 19.157244060668017


In [2]:
L1_norm_A = np.linalg.norm(A, ord=1, axis=1)
L2_norm_A = np.linalg.norm(A, ord=2, axis=1)

print("\nL1 norm of each row in A:\n", L1_norm_A)
print("\nL2 norm of each row in A:\n", L2_norm_A)

submatrix_A = A[:2, :2]
print("\nTop-left 2x2 submatrix of A:\n", submatrix_A)

alpha = 2
A_alpha = A * alpha
print("\nMatrix A scaled by alpha = 2:\n", A_alpha)

symmetric_A = np.dot(A.T, A)
print("\nSymmetric matrix A^T * A:\n", symmetric_A)

trace_A = np.trace(A)
print("\nTrace of A (sum of diagonal elements):\n", trace_A)

eigenvalues_A, eigenvectors_A = np.linalg.eig(A)
print("\nEigenvalues of A:\n", eigenvalues_A)
print("\nEigenvectors of A:\n", eigenvectors_A)

rank_A = np.linalg.matrix_rank(A)
is_full_rank_A = rank_A == A.shape[0]
print("\nIs A full rank? (True if full rank):\n", is_full_rank_A)

C = np.ones((3, 3))
sum_C_A = A + C
print("\nMatrix A after adding matrix C (all 1's matrix):\n", sum_C_A)

random_vector = np.random.randint(1, 10, 3)
diagonal_matrix = np.diag(random_vector)
print("\nDiagonal matrix from random vector:\n", diagonal_matrix)

is_orthogonal_A = np.allclose(np.dot(A, A.T), np.eye(A.shape[0]))
print("\nIs matrix A orthogonal? (True if orthogonal):\n", is_orthogonal_A)

D = np.random.randint(1, 10, (4, 4))
print("\nMatrix D (4x4 random matrix):\n", D)

try:
    D_inv = np.linalg.inv(D)
    print("\nInverse of D:\n", D_inv)
except np.linalg.LinAlgError:
    print("\nMatrix D is singular and does not have an inverse.")

if np.linalg.det(D) != 0:
    product_D_Dinv = np.dot(D, D_inv)
    print("\nD * D^-1 (Should be identity matrix):\n", product_D_Dinv)
else:
    print("\nCannot compute D * D^-1 because D is singular.")

B_calc = np.dot(np.dot(A.T, B), A)
det_D = np.linalg.det(D)
print("\nMatrix B = A^T * B * A:\n", B_calc)
print("\nDeterminant of D:\n", det_D)

try:
    D_inv_check = np.linalg.inv(D)
    print("\nInverse of D (calculated again):\n", D_inv_check)
except np.linalg.LinAlgError:
    print("\nD is still singular and cannot be inverted.")

identity_D = np.eye(4)
sum_D_I = D + identity_D
print("\nSum of D and identity matrix of size 4:\n", sum_D_I)

F = np.diag(np.random.randint(1, 10, 3))
print("\nMatrix F (random 3x3 diagonal matrix):\n", F)

is_diagonal_F = np.all(F == np.diag(np.diag(F)))
print("\nIs F diagonal? (True if diagonal):\n", is_diagonal_F)

F_mult_I = np.dot(F, np.eye(3))
print("\nF * I (should be equal to F):\n", F_mult_I)

trace_F = np.trace(F)
print("\nTrace of F:\n", trace_F)



L1 norm of each row in A:
 [17. 18. 14.]

L2 norm of each row in A:
 [11.44552314 12.08304597  9.48683298]

Top-left 2x2 submatrix of A:
 [[7 1]
 [1 8]]

Matrix A scaled by alpha = 2:
 [[14  2 18]
 [ 2 16 18]
 [ 2 16 10]]

Symmetric matrix A^T * A:
 [[ 51  23  77]
 [ 23 129 121]
 [ 77 121 187]]

Trace of A (sum of diagonal elements):
 20

Eigenvalues of A:
 [16.11103626  6.12015494 -2.2311912 ]

Eigenvectors of A:
 [[ 0.57525091  0.9875031  -0.57164616]
 [ 0.63838872 -0.13485713 -0.50972066]
 [ 0.51141591 -0.08155473  0.64296619]]

Is A full rank? (True if full rank):
 True

Matrix A after adding matrix C (all 1's matrix):
 [[ 8.  2. 10.]
 [ 2.  9. 10.]
 [ 2.  9.  6.]]

Diagonal matrix from random vector:
 [[1 0 0]
 [0 4 0]
 [0 0 9]]

Is matrix A orthogonal? (True if orthogonal):
 False

Matrix D (4x4 random matrix):
 [[6 8 2 6]
 [8 6 7 3]
 [5 8 5 5]
 [5 9 1 9]]

Inverse of D:
 [[ 0.23809524  0.17460317 -0.33333333 -0.03174603]
 [ 0.47619048 -0.31746032  0.33333333 -0.3968254 ]
 [-0.4

In [3]:
import numpy as np

def solve_system_inverse(A, B):
    try:
        A_inv = np.linalg.inv(A)
        solution = A_inv.dot(B)
        return solution
    except np.linalg.LinAlgError:
        return "Matrix is singular and cannot be inverted."

def solve_system_gauss(A, B):
    try:
        solution = np.linalg.solve(A, B)
        return solution
    except np.linalg.LinAlgError:
        return "No unique solution exists."

def check_solution_exists(A, B):
    try:
        solution = np.linalg.solve(A, B)
        return solution
    except np.linalg.LinAlgError:
        return "No solution exists or the system has infinite solutions."

def main():
    print("Bài 1: Giải hệ phương trình bằng phương pháp ma trận nghịch đảo")
    A1 = np.array([[2, 3, 1], [4, 1, 5], [3, 2, 4]])
    B1 = np.array([1, 2, 3])
    solution1 = solve_system_inverse(A1, B1)
    print("Nghiệm của hệ phương trình là:", solution1)

    print("\nBài 2: Giải hệ phương trình bằng phương pháp khử Gauss")
    A2 = np.array([[1, 2, 3], [2, 3, 1], [3, 1, 2]])
    B2 = np.array([7, 4, 5])
    solution2 = solve_system_gauss(A2, B2)
    print("Nghiệm của hệ phương trình là:", solution2)

    print("\nBài 3: Giải hệ phương trình với ma trận A và vector B đã cho")
    A3 = np.array([[1, 1, 1], [2, 3, 5], [4, 0, 5]])
    B3 = np.array([6, -4, 27])
    solution3 = solve_system_gauss(A3, B3)
    print("Nghiệm của hệ phương trình là:", solution3)

    print("\nBài 4: Xác định xem hệ phương trình có nghiệm hay không")
    A4 = np.array([[2, -3, 1], [4, -6, 2], [-1, 3, -1]])
    B4 = np.array([5, 10, -3])
    solution4 = check_solution_exists(A4, B4)
    print("Kết quả:", solution4)

    print("\nBài 5: Giải hệ phương trình không đồng nhất")
    A5 = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
    B5 = np.array([1, 0, 1])
    solution5 = solve_system_gauss(A5, B5)
    print("Nghiệm của hệ phương trình là:", solution5)

if __name__ == "__main__":
    main()


Bài 1: Giải hệ phương trình bằng phương pháp ma trận nghịch đảo
Nghiệm của hệ phương trình là: [-1.6  0.9  1.5]

Bài 2: Giải hệ phương trình bằng phương pháp khử Gauss
Nghiệm của hệ phương trình là: [0.22222222 0.55555556 1.88888889]

Bài 3: Giải hệ phương trình với ma trận A và vector B đã cho
Nghiệm của hệ phương trình là: [12.61538462 -1.92307692 -4.69230769]

Bài 4: Xác định xem hệ phương trình có nghiệm hay không
Kết quả: No solution exists or the system has infinite solutions.

Bài 5: Giải hệ phương trình không đồng nhất
Nghiệm của hệ phương trình là: [1. 1. 1.]
